Create копирование файла.cs
ZennoHelpers/Snippets pull request #11
Opened 2019-09-18 18:16 UTC by leotop

2019-09-18 18:58 UTC, lord-alfred requested changes
Необходимо доработать

2019-09-18 18:58 UTC, lord-alfred commented on Сниппеты/[Директории, Файлы]/копирование файла.cs
> +// Копирование файла в текущей директории проекта, для копирование внутри папки, добавить её вторым параметром в Path.Combine
"для копирование внутри" нужно "для копировани**я** внутри"

2019-09-18 18:58 UTC, lord-alfred commented on Сниппеты/[Директории, Файлы]/копирование файла.cs
> +
Название файла сделать с большой буквы

2019-09-18 18:58 UTC, lord-alfred commented on Сниппеты/[Директории, Файлы]/копирование файла.cs
> +string[] fromPaths = {directory, from_file_name};
Не обязательно создавать отдельную переменную-массив. Лучше сделать так:
```
string from = Path.Combine(directory, from_file_name);
```

2019-09-18 18:58 UTC, lord-alfred commented on Сниппеты/[Директории, Файлы]/копирование файла.cs
> +string to = Path.Combine(toPaths);
Тоже самое, лучше:
```
string to = Path.Combine(directory, to_file_name);
```

2019-09-24 08:42 UTC, leotop commented on Сниппеты/[Директории, Файлы]/копирование файла.cs
> +string[] fromPaths = {directory, from_file_name};
не согласен, переменная создана, для путей вида home/data/macro
в корне не так часто что-то лежит

2019-09-24 20:52 UTC, lord-alfred commented on Сниппеты/[Директории, Файлы]/копирование файла.cs
> +string[] fromPaths = {directory, from_file_name};
Не понял этот момент. Можешь подробнее объяснить?
Объясню свою логику: ты выше создаешь переменную-массив, которую используешь в 1 месте (только для передачи в виде 1 аргумента в `Path.Combine`, хотя можно не создавать переменную `fromPaths` (и `toPaths`) и передать содержимое их массивов внутрь `Path.Combine`. Разницы же абсолютно никакой не будет в плане работы, а вот сниппет станет короче, будет использовать меньше памяти - выгода же по всем фронтам от моего предложения. Или я может что-то не знаю?

2019-09-25 09:15 UTC, Zymlex commented on Сниппеты/[Директории, Файлы]/копирование файла.cs
> +string[] fromPaths = {directory, from_file_name};
> 
> 
> не согласен, переменная создана, для путей вида home/data/macro
> в корне не так часто что-то лежит

И вместо указания цельного пути, указывать имена папок раздельно.
В случае данной задачи, это несколько лишне.

2019-09-26 07:16 UTC, leotop commented on Сниппеты/[Директории, Файлы]/копирование файла.cs
> +string[] fromPaths = {directory, from_file_name};
Предлагаю сделать следующее. 1) Принять как есть 2) Следующим патчем кто-то из вас подправит сможет скорректировать код, под  единый удобный вид. У меня достаточно много заготовок, но пока не хватает времени полноценно этим заниматься.

2019-09-26 07:21 UTC, lord-alfred commented on Сниппеты/[Директории, Файлы]/копирование файла.cs
> +string[] fromPaths = {directory, from_file_name};
Не, так дело не пойдет. За каждым подправлять ходить - ни хватит не сил, не времени.

Никто не спешит ведь, как появится время - исправь. Мы же предлагаем исправления не ради того, чтоб "замучить" кого-то и отнимать время, а чтоб сниппеты были более-менее похожи друг на друга минимально, плюс чтоб они были всё же короткие (сниппеты же).

2019-09-26 07:28 UTC, leotop commented on Сниппеты/[Директории, Файлы]/копирование файла.cs
> +string[] fromPaths = {directory, from_file_name};
Изменил, проверьте.

2019-09-26 07:33 UTC, lord-alfred commented on Сниппеты/[Директории, Файлы]/копирование файла.cs
> +string[] fromPaths = {directory, from_file_name};
Отлично! Спасибо!

2019-09-26 07:33 UTC, lord-alfred approved these changes

2019-09-26 07:34 UTC, merged