IP в Int и обратно
ZennoHelpers/Snippets pull request #18
Opened 2019-09-20 15:37 UTC by BAZAg

2019-09-20 17:16 UTC, lord-alfred requested changes
Всё отлично работает!
Нужно исправить небольшие недочёты и я сделаю merge 👍

2019-09-20 17:16 UTC, lord-alfred commented on Сниппеты/[Прокси]/IP в Int и обратно.cs
> +		string[] absd = ip.Trim().Split('.');
Скорее всего ты подразумевал переменную с именем `abcd`? Или это не опечатка?

2019-09-20 17:16 UTC, lord-alfred commented on Сниппеты/[Прокси]/IP в Int и обратно.cs
> +	        }
Смешались пробелы с табами, нужно конвертировать в табы в этой строке )

2019-09-21 04:03 UTC, BAZAg commented on Сниппеты/[Прокси]/IP в Int и обратно.cs
> +		string[] absd = ip.Trim().Split('.');
Исправил

2019-09-21 04:03 UTC, BAZAg commented on Сниппеты/[Прокси]/IP в Int и обратно.cs
> +	        }
Исправил

2019-09-21 10:02 UTC, lord-alfred commented on Сниппеты/[Прокси]/IP в Int и обратно.cs
> +	        }
Если что - можно было просто в 1 строке поменять пробелы на табы и всё) А не все табы менять на пробелы во всем файле, но это так - к сведению :)

2019-09-21 10:03 UTC, lord-alfred approved these changes

2019-09-21 10:03 UTC, merged