Новые сниппеты + правки старых
ZennoHelpers/Snippets pull request #19
Opened 2019-09-21 22:27 UTC by Zymlex

2019-09-22 18:25 UTC, lord-alfred requested changes
Необходимы доработки

2019-09-22 18:25 UTC, lord-alfred commented on Сниппеты/[JS]/[Страница]/Высота с учетом прокрутки.js
> +);
Думаю, в конце стоит добавить: `return scrollHeight;` или поменять объявление переменной на `return`.

2019-09-22 18:25 UTC, lord-alfred commented on Сниппеты/[JS]/[Страница]/Изменение прокрутки.js
> +window.scrollTo(pageX,pageY); // абсолютные координаты,
Нужно показать как можно прокрутить до pageX, pageY, которые взяты из Zenno-переменных

2019-09-22 18:25 UTC, lord-alfred commented on Сниппеты/[JS]/[Страница]/Изменение прокрутки.js
> +window.scrollBy(x,y); // прокрутить относительно текущего места.
Тут нужно как-то по-другому описать пример, т.к. сходу не ясно в чем отличие - хочется идти гуглить в чем отличие `scrollTo` от `scrollBy`

2019-09-22 18:25 UTC, lord-alfred commented on Сниппеты/[JS]/[Страница]/Изменение прокрутки.js
> +elem.scrollIntoView(top); // прокрутить, чтобы элемент elem стал виден.
`elem` и `top` не объявлены, да и по доке там как-то по-другому вроде работает(?): https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView

2019-09-22 18:25 UTC, lord-alfred commented on Сниппеты/[JS]/[Страница]/Отслеживание изменения координат элемента.js
> +function onElementRectChange(node, callback) {
Классная и очень полезная функция, но опять же нужен пример как её заюзать (я скоре всего разберусь, но не хочется сильно напрягаться и хочется просто подставить свой элемент и поменять тело функции колбека :)

2019-09-22 18:25 UTC, lord-alfred commented on Сниппеты/[JS]/[Страница]/Получение координат.js
> +	var box = elem.getBoundingClientRect();
Микс табов и пробелов

2019-09-22 18:25 UTC, lord-alfred commented on Сниппеты/[JS]/[Страница]/Получение координат.js
> +    top box.top + pageYOffset,
Вроде бы тут и в следующей строке опечатка, не понимаю откуда там `top` и `left` перед выражениями.
Скорее всего двоеточия пропущены (или это 6 ecmascript, но без `use strict;` не баганет ли зенка на этом?)

2019-09-22 18:25 UTC, lord-alfred commented on Сниппеты/[JS]/[Страница]/Получение координат.js
> +function getCoords(elem){
Опять же - полезен пример вызова, но тут ещё и возвращаемое значение вернется в виде объекта, поэтому полезно показать как работать дальше

2019-09-22 18:25 UTC, lord-alfred commented on Сниппеты/[JS]/unixtime.js
> +new Date().getTime();
Нехватает `return`

2019-09-22 18:25 UTC, lord-alfred commented on Сниппеты/[JS]/Проверка наличие вложенного свойства.js
> +const fn = function (obj, props) {
Опять же - полезен пример вызова, плюс тут на сколько я понимаю - `props` могут быть несколько, а название по 1 свойство. Непонятно :)

2019-09-22 18:25 UTC, lord-alfred commented on Сниппеты/[JS]/Проверка наличие вложенного свойства.js
> +};
если свойство присутствует, может стоит добавить return? Вообще код не выглядит рабочим, если честно (но я его не запускал - могу ошибаться).

2019-09-22 18:25 UTC, lord-alfred commented on Сниппеты/[JS]/Расчёт формулы в строке.js
> +Math.round(eval('5+0.01+0.34-5*1') * 100) / 100;
Имеет смысл показать как из zenno-переменных туда что-то передать в eval

2019-09-22 18:25 UTC, lord-alfred commented on Сниппеты/[Логика]/Пауза (потока).cs
> +System.Threading.Thread.Sleep(1000);
Ты не знаешь разницу с:
```
new System.Threading.ManualResetEvent(false).WaitOne(1000);
```

Я его всегда юзаю, а вот почему - не помню, уже давно так )

2019-09-22 18:25 UTC, lord-alfred commented on Сниппеты/[Списки]/Поиск частичного совпадения в списке.cs
> +// берем из переменной текст, который надо искать
Уже есть: https://github.com/ZennoHelpers/Snippets/blob/master/Сниппеты/%5BСписки%5D/Проверка%20содержит%20ли%20список%20какую-то%20конкретную%20строку.cs

2019-09-22 18:25 UTC, lord-alfred commented on Сниппеты/[Списки]/Поиск элемента в списке.cs
> +IZennoList list = project.Lists["BlackList"];
Лучше название "Проверка присутствия элемента в списке", потому что "Поиск элемента" - подразумевает возвращение его позиции, по-моему.

2019-09-22 18:25 UTC, lord-alfred commented on Сниппеты/[Списки]/Удаление дублей в списке.cs
> +	for (int i=0; i < project.Lists["buildID"].Count; i++)
Можно проще, без перебора:
```
HashSet<string> hs = new HashSet<string>(project.Lists["buildID"]);
project.Lists["buildID"].Clear();
project.Lists["buildID"].AddRange(hs);
```

2019-09-22 18:25 UTC, lord-alfred commented on Сниппеты/[Текст]/Смена кодировки строки.cs
> +string initial = "utf-8";
Добавить комментарий что это исходная кодировка

2019-09-22 18:25 UTC, lord-alfred commented on Сниппеты/[Текст]/Смена кодировки строки.cs
> +string target = "cp866";
А тут что это получаемая в результате кодировка

2019-09-22 20:15 UTC, Zymlex commented on Сниппеты/[JS]/unixtime.js
> +new Date().getTime();
> 
> 
> Нехватает `return`

Если выполнять локально, то не сработает.

2019-09-22 20:38 UTC, Zymlex commented on Сниппеты/[Логика]/Пауза (потока).cs
> +System.Threading.Thread.Sleep(1000);
> ```
> new System.Threading.ManualResetEvent(false).WaitOne(1000);
> ```

Припоминаю, ManualResetEvent(false) это тот что не блокирует GUI, вроде?

2019-09-22 20:40 UTC, Zymlex commented on Сниппеты/[JS]/[Страница]/Отслеживание изменения координат элемента.js
> +function onElementRectChange(node, callback) {
Думаю, пример теперь куда лучше. Тестить лучше в браузере.

2019-09-23 09:42 UTC, lord-alfred approved these changes

2019-09-23 09:42 UTC, merged